### ISSUE TITLE
Error when calling 'Add to playlist' with a Playlist path

### ISSUE THREAD

**Issue by GrantDG** [3ll3d00d/jriver_homeassistant#24]
I'm attempting to execute an 'Add to playlist' action with a playlist path. The following error is being logged:

`Error: JRiverMediaPlayer.async_add_media_to_playlist() missing 1 required positional argument: 'query'`

The automation YAML is:

```YAML
alias: Test JRiver Add To Playlist
description: ""
triggers: []
conditions: []
actions:
  - action: jriver.add_to_playlist
    metadata: {}
    data:
      playlist_path: Morning Music\Acid Jazz
    target:
      device_id: aefb9c9d12424ae7d504c8353e297e4d
mode: single

```

**Comment by GrantDG** [comment]
I did some more experimentation on this.

- I 'exported' my smartlist definition as a query, and pasted to the 'Search Query' field, and deselected 'Playlist path'. This resulted in an error of `Error: JRiverMediaPlayer.async_add_media_to_playlist() missing 1 required positional argument: 'playlist_path'`
- After this I added a 'Playlist path' of ' ' (a single space). This resulted in successful execution on JRiver, however, the playlist 'replaced' the playing now list, rather than appending.
- Next I inverted the above and Used a proper 'Playlist path' with a 'Search query' of ' ' (a single space). This resulted in Crashing JRiver!

**Comment by 3ll3d00d** [comment]
it's a bug for sure, I tell HA that each item is optional but it insists on a value anyway and I don't know how to get HA to respect this choice. I probably I have to make two separate services instead.

crashing MC given an empty string is probably a thing to raise with them as it just gets passed through to MCWS hence must be a bug there

there's no option in MCWS to append a playlist that I can see, only to play it, this would be another thing to raise with JRiver to see if they'll add such a feature. A search is appended though.

**Comment by GrantDG** [comment]
> crashing MC given an empty string is probably a thing to raise with them as it just gets passed through to MCWS hence must be a bug there

If there's a fix on your side, I won't need to send the empty string. This was more of a testing/investigation item.

> there's no option in MCWS to append a playlist that I can see, only to play it, this would be another thing to raise with JRiver to see if they'll add such a feature. A search is appended though.

The HA action is called "JRiver Media Center 'Add to playlist'" - maybe that further points to there needing to be 2 different actions, if the Playlist one can't actually 'Add to playlist'. Maybe could be a new "JRiver Media Center 'Play playlist'"?

**Comment by 3ll3d00d** [comment]
I don't think MC should crash if you send an empty string so that seems like a bug regardless

I will split it into two (or three) services

**Comment by 3ll3d00d** [comment]
should be fixed in 0.4.0

**Comment by GrantDG** [comment]
I can confirm that the 'Play playlist' action is working as expected...

However, the 'Playlist path' parameter still exists on the 'Add to playlist' action (not a problem for me, but may cause confusion to someone!)

Also, is there a way to make a parameter 'mandatory' in an MA action? It's currently possible to add the 'Play a playlist' action and not specify a playlist. 
I do get a reasonably descriptive error on execution.

**Comment by 3ll3d00d** [comment]
I will delete the original service in the next release as it's basically broken anyway

I can't find a way to make it actually mandatory, I already tell HA that the value is "required" but it seems to ignore this info so not sure there is anything else I can do
